name: project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  http: ^1.1.0
  mockito: ^5.4.3
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/   # Add this line to include the images directory
